#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not support the $ (command substitution) syntax, POSIX shells like dash, ash, and others
#       can be used instead.
#
#   (2) Put the POSIX shell executable in the shebang above.
#
#   (3) Remove "-Dtrace.openj9" if running the OpenJ9 JVM.
#
##############################################################################

# shellcheck disable=SC2006
basedir=$( cd "$(dirname "$0")" || exit ; pwd -P )

##############################################################################
# Start of user customizable section
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

##############################################################################
# Lower the file descriptors to avoid the "Too many open files" error,
# but still allow enough file descriptors to work with the gradle build.
#
for (( i=3; i<MAX_FD; i++ )); do
    eval "exec $i>&-"
done
unset i

# Allow when being sourced by bash
if [ -z "$BASH_VERSION" ] ; then
    set +e
fi

##############################################################################
# End of user customizable section
##############################################################################

set +e

# Resolve links this shell variable may have stdin redirection.
while :
do
    ls -ld "$basedir" 2>/dev/null | grep ' -> ' > /dev/null
    if [ $? -ne 0 ] ; then
        break
    fi
    basedir=$( cd "$(dirname "$basedir")" || exit ; pwd -P )
done

export CLASSPATH="$basedir/gradle/wrapper/gradle-wrapper.jar"

APP_HOME=$basedir

exec "$JAVACMD" \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
